version: 0.2

version: 0.2

env:
  secrets-manager:
    DOCKERHUB_PASS: "dockercredentials:password"
    DOCKERHUB_USERNAME: "dockercredentials:username"

phases:
  install:
    commands:
      - echo pre_build step...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - make all
