version: 0.2

phases:
#   pre_build:
#     commands:
#       - echo Logging in to Docker Hub...
#       - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin 
  build:
    commands:
      - make all
